---
- hosts: all
  become: yes
  become_user: master
  tasks: 
  ##check ping
    - name: Ping check host
      ping: ~
  # install docker
    - name: Install Docker
      apt: name=apache2 update_cache=yes