---
- hosts: all
  tasks: 
 
    - name: Ping check host
      ping: ~
 
    - name: stop nginx
      service:
          name: nginx
          state: stopped
    - name: ensure nginx is not installed
      apt: name=nginx state=absent