---
- hosts: all
  tasks: 
 
    - name: Ping check host
      ping: ~
 
    - name: Run container
      become: True
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d"
        chdir: /