---
- hosts: all
  tasks: 
 
    - name: Ping check host
      ping: ~

    - name: update source
      become: True
      shell:
        cmd: "git clone "https://github.com/kiemsibat/web-projec-lanh1.git""
        chdir: /home/slave/jenkins/workspace/

    - name: Stop container
      become: True
      shell:
        cmd: "docker-compose down"
        chdir: /home/slave/jenkins/workspace/ansible-demo

    - name: Rebuild container
      become: True
      shell:
        cmd: "docker-compose build --no-cache"
        chdir: /home/slave/jenkins/workspace/ansible-demo

    - name: Run container
      become: True
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d"
        chdir: /home/slave/jenkins/workspace/ansible-demo